Repository Swiftbook-Middle-iOS/MdEditor, pull requests merged in 2024-01, with the labels that each got.

#20 M3L305-Added tests for DoublyLinkedList
  DataStructuresPackage/Package.swift
  DataStructuresPackage/Sources/DataStructuresPackage/DoublyLinkedList.swift
  DataStructuresPackage/Tests/DataStructuresPackageTests/DoublyLinkedListTests.swift
Labels: В работе

#17 M3L302 - Создание тестов для TaskManager
  TaskManagerPackage/Tests/TaskManagerPackageTests/TaskManagerPackageTests.swift
Labels: В работе

#18 M3L303 - Создание тестов для OrderedTaskManager
  TaskManagerPackage/Tests/TaskManagerPackageTests/OrderedTaskManagerPackageTests.swift
Labels: В работе

#30 Mamlygo/m3l3 Test Fixes
  DataStructuresPackage/Sources/DataStructuresPackage/DoublyLinkedList.swift
  DataStructuresPackage/Sources/DataStructuresPackage/Queue.swift
  DataStructuresPackage/Tests/DataStructuresPackageTests/DoublyLinkedListTests.swift
  DataStructuresPackage/Tests/DataStructuresPackageTests/QueueTests.swift
Labels: bug

#45 Gulyaev/m3l506
  Project/Sources/Scenes/Login/LoginViewController.swift
  Project/Sources/Scenes/TodoList/TodoListViewController.swift
Labels: Выполнено
